[package]
name = "rmqtt-sys-topic"
version = "0.1.1"
description = "RMQTT periodically publishes its own operational status, message statistics, and client online/offline events to system topics starting with $SYS/."
repository = "https://github.com/rmqtt/rmqtt/tree/master/rmqtt-plugins/rmqtt-sys-topic"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmqtt = { workspace = true, features = ["plugin", "msgstore", "stats", "metrics"] }
tokio = { workspace = true, features = ["sync", "time"] }
serde = { workspace = true, features = ["derive"] }
async-trait.workspace = true
log.workspace = true
serde_json.workspace = true
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true


