[package]
name = "rmqtt-web-hook"
version = "0.1.3"
description = "This enables RMQTT to send hook event notifications to a web service."
repository = "https://github.com/rmqtt/rmqtt/tree/master/rmqtt-plugins/rmqtt-web-hook"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmqtt = { workspace = true, features = ["plugin"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync", "fs","io-util"] }
rust-box = { workspace = true, features = ["task-exec-queue"] }
async-trait.workspace = true
log.workspace = true
serde_json.workspace = true
anyhow.workspace = true
backoff = { workspace = true, features = ["futures", "tokio"] }
base64.workspace = true
bytestring.workspace = true
reqwest = { workspace = true, features = ["json"] }
futures.workspace = true
chrono.workspace = true
ahash.workspace = true
url.workspace = true



