[package]
name = "simple_ws"
version = "0.1.0"
edition.workspace = true

[dependencies]
rmqtt = { workspace = true, features = ["ws"] }
tokio = { version = "1", features = ["full"] }
simple_logger = "5"
log = "0.4"

